#docker compose for start all containers needed for our application
#docker compose is very similar to kubernetes

version: "3.1"
services:
  db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - data_container:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  webapp:
    build: .
    environment:
      - EMAILUSER=letterrecommender@gmail.com
      - EMAILPASS=USCPassword123!
      - PORT=30
    ports:
      - "443:443"
      - "3000:3000"
      - "80:80"
    depends_on:
      - db
      - redis

#a container for database data for data persistence
volumes:
  data_container:
